openapi: 3.0.0
info:
  title: RAG Chatbot API
  version: 1.0.0
paths:
  /api/query:
    post:
      summary: Submit a RAG query
      operationId: queryKnowledgeBase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RAGQueryRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RAGQueryResponse'
components:
  schemas:
    RAGQueryRequest:
      type: object
      required:
        - query_text
        - session_id
      properties:
        query_text:
          type: string
        session_id:
          type: string
        selected_context:
          type: string
          nullable: true
    RAGQueryResponse:
      type: object
      required:
        - answer
        - session_id
      properties:
        answer:
          type: string
        session_id:
          type: string
        evaluation_scores:
          type: object
          properties:
            relevance:
              type: number
            faithfulness:
              type: number
