openapi: 3.0.0
info:
  title: RAG Query API
  version: 1.0.0
  description: API for Retrieval-Augmented Generation (RAG) queries against the "Physical AI & Humanoid Robotics" book content.

paths:
  /api/rag/query:
    post:
      summary: Submit a query to the RAG system and get a contextual answer.
      description: This endpoint orchestrates the RAG process, performing vector search, context lookup, and LLM generation. It also supports a "highlight-to-query" feature via the `context_snippet` parameter.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RAGQueryRequest'
      responses:
        '200':
          description: Successful response with a contextual answer.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RAGQueryResponse'
        '400':
          description: Bad request, e.g., invalid input format.
        '500':
          description: Internal server error, e.g., issues with OpenAI API or database connections.

components:
  schemas:
    RAGQueryRequest:
      type: object
      properties:
        query:
          type: string
          description: The user's natural language question.
          example: "What are the core components of ROS 2?"
        context_snippet:
          type: string
          nullable: true
          description: An optional text snippet (e.g., highlighted text) to prioritize as context for the LLM. If provided, bypasses RAG search.
          example: "ROS 2's architecture includes nodes, topics, services, and actions. Nodes are processes that perform computation."
      required:
        - query
      
    RAGQueryResponse:
      type: object
      properties:
        answer:
          type: string
          description: The contextual answer generated by the LLM, based on the provided query and context.
          example: "The core components of ROS 2 architecture include nodes, topics, services, and actions, which are used to manage computational processes and inter-node communication."
        sources:
          type: array
          items:
            $ref: '#/components/schemas/SourceMetadata'
          nullable: true
          description: Optional list of metadata for the source chunks used to generate the answer.
      required:
        - answer

    SourceMetadata:
      type: object
      properties:
        chunk_id:
          type: string
          format: uuid
          description: Unique identifier of the text chunk.
          example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
        chapter_title:
          type: string
          description: The title of the chapter the chunk belongs to.
          example: "Chapter 1: ROS 2 Architecture"
        page_number:
          type: integer
          description: The page number from which the chunk was extracted.
          example: 42
